// generated by edgejobber for test-job
import { nanoid } from 'nanoid';
import { add } from '../../src';
import { job } from '../../src/job';

@job("test-job")
export class MyJob {
    run() {
        const id = nanoid();
        console.log('Generated ID:', id);
        const sum = add(10, 10);
        console.log('Sum:', sum);
        return { id, sum };
    }
}

export default MyJob;
