// generated by edgejobber for test-job-2
import { add } from '../../src';
import { job } from '../../src/job';

@job("test-job-2")
export class MyJob2 {
    run() {
        const sum = add(10, 10);
        console.log('Sum:', sum);
        return { sum };
    }
}

export default MyJob2;
